### ISSUE TITLE
launch tensor module before stylized picture.

### ISSUE THREAD

**Issue by shenbuqingyun** [MashirosBaumkuchen/Flora#3]
I don not know about tensor, what is the meaning of "launch tensor module before stylized picture?" Some kind of operator?

**Comment by shenbuqingyun** [comment]
Thank you!

**Comment by jascals** [comment]
为了解决tensorflow模型造成的oom问题，项目使用了多进程模式。此外因为本身是一个demo app，也是为了练手，所以当时兴趣使然做成了两个独立的模块app和tensor，app依赖tensor，如果tensor没有下载，就无法使用相应的方法。
建议你在调试前安装下tensor模块；或者在single_app_model分支下直接调应用；或者将tensor模块封装在一个new_process的service中。
这个部分没有维护的计划，学生党精力有限QAQ。。。
