### ISSUE TITLE
How to build an release APK

### ISSUE THREAD

**Issue by shenbuqingyun** [MashirosBaumkuchen/Flora#4]
what`s the most important question is how to build an release apk? I can not launch tensor first and then build apk.

**Comment by shenbuqingyun** [comment]
Thank you!

**Comment by jascals** [comment]
可以把tensor model跑在默认进程中
也可以在manifest中对tensor service设置新进程，处理图像任务（推荐）

**Comment by shenbuqingyun** [comment]
Thanks! it works.
